name: Build and Package Wheels

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.cibw_python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cibw_python: ["cp310-manylinux_x86_64", "cp311-manylinux_x86_64", "cp312-manylinux_x86_64"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.21.3

      - name: Build wheels via cibuildwheel
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_BEFORE_ALL_LINUX: >
            dnf install -y libX11-devel mesa-libGL-devel vulkan-loader-devel libXcursor-devel libXrandr-devel libXinerama-devel libXi-devel

          CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
            auditwheel repair -w {dest_dir} {wheel} --exclude libGL.so.1 --exclude libvulkan.so.1 --exclude libX11.so.6 --exclude libxcb.so.1 --exclude libXau.so.6 --exclude libXdmcp.so.6
          CIBW_TEST_REQUIRES: "pytest>=7.0.0"
          CIBW_TEST_COMMAND: "pytest {project}/tests"

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.cibw_python }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution (sdist)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build
        run: python -m pip install --upgrade build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
